### ISSUE TITLE
Add the reminder as first in the list instead of last

### ISSUE THREAD

**Issue by Birowsky** [surrealroad/alfred-reminders#107]
Is there a way for me to configure something to have the new item be added as first instead of last?

Thanks!

**Comment by Jish2** [comment]
A couple years late to this 😁

in this script:

<img width="758" alt="image" src="https://github.com/surrealroad/alfred-reminders/assets/25201575/a2b7b7c3-e5b7-4c4a-8cdf-da8053e2e0e4">

you can edit line 49 to "unshift"

before
<img width="335" alt="image" src="https://github.com/surrealroad/alfred-reminders/assets/25201575/45818be1-49f1-4fb0-b3fa-ca65fba04ba1">

after
<img width="352" alt="image" src="https://github.com/surrealroad/alfred-reminders/assets/25201575/e53d1b1a-ab97-40b2-984e-2536f4bf0b63">

**Comment by Birowsky** [comment]
Beautiful, thanks!
