### ISSUE TITLE
Support # for list definition

### ISSUE THREAD

**Issue by stephenrjohnson** [surrealroad/alfred-reminders#113]
At the moment you have to do in (list) list, I'm just wondering if adding #(list) to define the list would be an issue?

**Comment by rkabrick** [comment]
I'd much rather utilize the `#` to add tags. Tags & smart lists are definitely the way to go imo

**Comment by moderatoburrito** [comment]
Agreed with @rkabrick! Tagging support would be great, and # is the most obvious way to go there.

**Comment by Doslin** [comment]
I'll keep an eye on that

**Comment by trijste** [comment]
+1 for tag support. I tried it instinctively and was disappoint :(

**Comment by rejozenger** [comment]
+1 for tag support. Like previous commenter, also used it instinctively and also... :)

**Comment by surrealroad** [comment]
I agree this would be a great feature, but as far as I can tell Apple has not provided any way to manage tags on reminders through applescript. If anyone can prove me wrong, now or in the future, I'd happily look into it!
