### ISSUE TITLE
Current binary doesn't match with main branch

### ISSUE THREAD

**Issue by crierr** [surrealroad/alfred-reminders#114]
Current binary doesn't match with main branch.
Version is 74 when building from source, on the contrary version is 75 when installing Reminders.alfredworkflow.
It seems like some changes missed in PR #112

**Comment by crierr** [comment]
I was trying to make Reminder widget in notification center updated by alfred-reminders. Adding little delay (2s) before quitting Reminders app solved the issue, but I wonder if it is ok to upload binary built from current source.

**Comment by surrealroad** [comment]
Binary should now be up to date, sorry about that
