### ISSUE TITLE
Frequently prompted to update

### ISSUE THREAD

**Issue by valochelb** [surrealroad/alfred-reminders#128]
Hi, I use this workflow all the time and absolutely love it, but I noticed for a long time now that I am very frequently prompted to update the workflow with the Alfred app opening like once every other week, which is a little bit cumbersome and disruptive, but I see on the GitHub page that the last version is from October 2021.

I tried uninstall and reinstall it but it didn't resolve the issue

Thanks for your help !

**Comment by surrealroad** [comment]
Sorry don't know why it's happening (it happens to me also). You can try just deleting the connection to the update checker (it's probably not needed as you pointed out this workflow is no longer updated)
![image](https://github.com/surrealroad/alfred-reminders/assets/61921/9f549543-bfd1-4f33-b4f9-73bc18d6cd0d)

**Comment by valochelb** [comment]
No worries ! I deleted the connection hopefully it'll do it, I really like this workflow

**Comment by waharris007** [comment]
I've had the same issue forever. Just checked here to find the suggestion to kill the updater connection, and now it works perfectly. Thanks!

**Comment by surrealroad** [comment]
Fixed in c65a95ae23184772d12cc29b3629a9d268abe675
