### ISSUE TITLE
Multiple Install Update Notices on Alfred 5.5

### ISSUE THREAD

**Issue by tonydehnke** [surrealroad/alfred-reminders#133]
Hi,  I am getting random, multiple update notices for the Reminders plug-in.  I had updated to v74, but then this morning I was prompted to install v74 again twice in a few minutes (which I did both times). 

Do you have any ideas what is going on?

Alfred 5.5
Reminders v74
MacOS 14.5 (23F79)

**Comment by surrealroad** [comment]
Could you post a screenshot? The autoupdate should be disabled since the past few releases

**Comment by tonydehnke** [comment]
This was the one when it was on v74
![Untitled](https://github.com/surrealroad/alfred-reminders/assets/36720180/59d3f6a7-9da3-4383-b946-9d5a45164205)

![Untitled2](https://github.com/surrealroad/alfred-reminders/assets/36720180/1d475c92-dbc3-4655-aab1-291bec3f44f9)

**Comment by tonydehnke** [comment]
Weird - I've deleted 3 twice now (via the Alfred app), but it keeps coming back. 

![Untitled](https://github.com/surrealroad/alfred-reminders/assets/36720180/abd12b8f-fa4e-4164-9716-89be4d309a7b)

**Comment by surrealroad** [comment]
Not sure what's happening here. I would suggest delete both workflows, quit/restart Alfred, make sure neither is there, and then try reinstalling v79.

**Comment by tonydehnke** [comment]
Just manually deleted the old Reminders Folder in the workflows folder via Terminal command  - finder would not let me delete it.  I'm guessing that maybe the file system/folder got stuck in some weird state. 

Alfred restarted fine and I can't see it now.  

Will come back to this if it pops up again - but I can't see that happening now that the folder is nuked.

**Comment by tonydehnke** [comment]
Closing for now
