### ISSUE TITLE
Reminders Command Not Recognised

### ISSUE THREAD

**Issue by joshvickerson** [surrealroad/alfred-reminders#16]
Just installed the workflow on 10.10 and the command isn't recognised. I tried restarting Alfred with no luck. Here's what I see: 
![screen shot 2014-10-21 at 2 55 26 pm](https://cloud.githubusercontent.com/assets/2325487/4724815/0fc98cac-5954-11e4-93f0-e48e51dfecf2.png)
![screen shot 2014-10-21 at 2 56 59 pm](https://cloud.githubusercontent.com/assets/2325487/4724821/146ddc68-5954-11e4-9e19-8b9d97c8ae8f.png)

Neither Alfred nor this script appear in apps requesting access to Reminders in System Settings.

**Comment by dandineen** [comment]
Hi there,

I seem to be having the same behaviour as those above except on El Capitan (10.11.1). I installed the workflow this morning (01/11/15) from this Github repo. 

Typing 'r ' into Alfred returns 'Reminder command not recognised or no matching reminders found'. I do briefly see a flash of the 'Type the name of a reminder...' message before it changes to 'Reminder command not recognised'.

Any thoughts? :-)

**Comment by surrealroad** [comment]
Typing "r " won't do anything. The usage is "r <command>". You can type "r help" for some examples.

**Comment by surrealroad** [comment]
Anyone on this thread still having issues with Alfred v3 and macOS Sierra, please try this new version http://bit.ly/2gkUsQf
