### ISSUE TITLE
how to set default list?

### ISSUE THREAD

**Issue by haemi** [surrealroad/alfred-reminders#26]
you wrote ```I didn't consider that possibility! Download the updated version in the original post, and you can set the name of the list to use at the top of the applescript``` but unfortunately I didn't find the place to set the default list...

**Comment by surrealroad** [comment]
![alfred_preferences](https://cloud.githubusercontent.com/assets/61921/9274749/22dc52b8-4290-11e5-80cc-2d4864068995.png)
Edit these items:

![screenshot_14_08_2015_14_24](https://cloud.githubusercontent.com/assets/61921/9274764/436c7e5e-4290-11e5-9e31-fdfe6d83801c.png)
