### ISSUE TITLE
r in 2 days do something doesn't work

### ISSUE THREAD

**Issue by contentfree** [surrealroad/alfred-reminders#28]
Just updated to the latest and trying to enter `r in 2 days do something` appears to do nothing (debug output shows an error even though it seems to think it's a valid command).

Here's the debug output:

```
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item uid="add-reminder" arg="in 2 days do something" type="file" valid=""><title>Add Reminder</title><subtitle>Create a new reminder to do something on Saturday, December 5, 2015 at 12:22:07 PM</subtitle><icon>unchecked.png</icon></item></items>
[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.action.script' with arg 'in 2 days do something'
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg 'Could not understand command "in 2 days do something"
```

**Comment by Haseong** [comment]
r in 2 days 0 hour something does work

**Comment by contentfree** [comment]
@Haseong True. Strange that adding "0 hour" allows it to process the command…

**Comment by kropsi** [comment]
bump

**Comment by surrealroad** [comment]
Currently only the following will work:
`r in {X} days {Y} hours …`
`r in {X} days at {time} to …`

**Comment by surrealroad** [comment]
Fixed in https://github.com/surrealroad/alfred-reminders/commit/2241da9e15bd6a16b90e10d71fec9e0a3f7d31ab
You can now do `r in 2 days do something`
