### ISSUE TITLE
"r all" doesn't work

### ISSUE THREAD

**Issue by coryfklein** [surrealroad/alfred-reminders#33]
Just installed alfred-reminders workflow. I've used it to create a reminder, and that worked fine. However, "r all" doesn't appear to work:

![image](https://cloud.githubusercontent.com/assets/3503322/13536149/8f77f1ba-e1fb-11e5-8d14-0ed8ba16fcae.png)

"r help" works though...

![image](https://cloud.githubusercontent.com/assets/3503322/13536162/a24c7bc6-e1fb-11e5-8fa0-524b4a91e00b.png)

**Comment by surrealroad** [comment]
"r all" is currently not supported on Mac OS X 10.9+ due to a bug in the OS.

**Comment by coryfklein** [comment]
@surrealroad Thanks.
