### ISSUE TITLE
can't  not recognise the time and data

### ISSUE THREAD

**Issue by Anotherbuzz** [surrealroad/alfred-reminders#34]
hello. thank you for making this excellent workflows. I've used it for about 2 weeks and it worked well until today. i suddenly can't recognise the time and data even though I  tried to use your example.

the system version is el Capitan 10.11.4 beta (15E61b), I haven't done any system updates during these days.
here are the screenshots.
<img width="594" alt="captura de pantalla 2016-03-16 a las 2 25 04 p m" src="https://cloud.githubusercontent.com/assets/17637450/13803937/a4e0a088-eb83-11e5-8dbb-1b6355e5cc17.png">
<img width="594" alt="captura de pantalla 2016-03-16 a las 2 25 20 p m" src="https://cloud.githubusercontent.com/assets/17637450/13803938/a4e1e20e-eb83-11e5-8039-2e0441a9c030.png">

thanks a lot for your help.

**Comment by surrealroad** [comment]
it should be "r at 12pm to something" or "r today something"
