### ISSUE TITLE
the rshow command does not work

### ISSUE THREAD

**Issue by Anotherbuzz** [surrealroad/alfred-reminders#35]
hi, i can't not use the rshow command as well as the "r today" o "r tomorrow " to view the existing reminds
<img width="594" alt="captura de pantalla 2016-03-16 a las 2 51 51 p m" src="https://cloud.githubusercontent.com/assets/17637450/13804292/a44ace8e-eb86-11e5-8db5-199cea0d7f34.png">
. here are the screenshots

<img width="594" alt="captura de pantalla 2016-03-16 a las 2 48 50 p m" src="https://cloud.githubusercontent.com/assets/17637450/13804236/48056026-eb86-11e5-87ef-2ae6e9d54bb9.png">
<img width="594" alt="captura de pantalla 2016-03-16 a las 2 49 06 p m" src="https://cloud.githubusercontent.com/assets/17637450/13804238/48c88c04-eb86-11e5-90ce-f17c22d106e2.png">

system version: El Capitan 10.11.4 beta (15E61b)

thanks a lot.

**Comment by surrealroad** [comment]
Displaying reminders is not supported on OS 10.11

> This workflow currently operates in a "write-only" mode in OS 10.9 or later.
> Due to an issue with OS 10.9 (and likely 10.10), I have removed some of the functionality– specifically the ability to view current reminders within Alfred. You can still use all the commands for adding new reminders, and in the event that the issue is fixed, I will restore full functionality. Read on if you want more details on why this is.
>  
> When using this workflow with 10.9+, performance is extremely slow (14x slower than 10.8) due to an apparent bug in osascript (which may affect other Alfred workflows too, or might just be limited to accessing Reminder data). This means that fetching data from Reminders is taking around a minute or so per reminder. This is a reproducible bug with AppleScript that has nothing to do with Alfred or this workflow, which I have logged with Apple as of October 7 (#15163843), but has not yet been addressed (and as with other bugs, may never be).
>  
> The workflow is designed to use a caching process to store current reminders (as trying to access them directly on any OS version is somewhat slow), but even this can result in prolonged CPU spikes while the cache is built in 10.9+, as well as general unresponsiveness of Reminders.
>  
> This is probably the best I can do for now until the bug gets fixed (which might never happen). I am genuinely sorry about this, and if I can figure out a way around it, I will do so, but ultimately the workflow has to communicate with Reminders via AppleScript to some extent.

**Comment by Anotherbuzz** [comment]
ok, got it. thanks a lot and sorry for troubling you.
