### ISSUE TITLE
Default list

### ISSUE THREAD

**Issue by rsambuelli** [surrealroad/alfred-reminders#36]
Hi,
I have my default reminders list to my iCloud account, but the workflow create the entries in the "on my Mac" list. (v10.11)
Sorry to bother, but couldn't find where the script sets the folder.
Thanks,

rs.-

**Comment by rsambuelli** [comment]
easy, just deleted "on my mac" list.
thanks anyway. and thanks for the workflow. the best option available by far even with OS compatibility limitations.

**Comment by surrealroad** [comment]
Sorry I'm coming to this so late, but you can actually set the default list by editing the workflow, see here: https://github.com/surrealroad/alfred-reminders/issues/26

**Comment by rsambuelli** [comment]
Thanks!!
