### ISSUE TITLE
"r this ..." fails entirely

### ISSUE THREAD

**Issue by brandondrew** [surrealroad/alfred-reminders#38]
This is probably related to the other issue mentioning "r this", but the behavior described there is quite different.

When I enter "r this <anything else>" the word "this" is apparently being evaluated at some point in the code and causing a problem, rather than being treated as a string from start to finish.

![image](https://cloud.githubusercontent.com/assets/9854/16207600/f62ad4c2-36fb-11e6-9d87-ff53b4fcd039.png)

It happens regardless of whether there is text after "this".

![image](https://cloud.githubusercontent.com/assets/9854/16207518/859faa52-36fb-11e6-92e0-d6cb43f605db.png)

Quoting "this" with either single or double quotes does not help at all.

If this is a bug in Alfred, has it been reported to Running With Crayons?

**Comment by brandondrew** [comment]
Or, I should say "a limitation imposed by Alfred" since there is presumably some value in being able to refer to the currently open app with a keyword like "this".

A good solution would be if Alfred allowed certain workflows to turn that feature off, so that `r this` does _not_ refer to the current app with `this`, but `some-other-workflow this` _does_.

**Comment by surrealroad** [comment]
I'm not sure what your issue is here.. "r this" is intended to capture information from the foreground window as a reminder. So if you're using Safari, "r this" will create a reminder about the current URL. It looks like what you actually want to achieve is simply "r friday to eat spinach".

**Comment by brandondrew** [comment]
Okay, I didn't notice that `this` is actually a part of the syntax supported by Alfred Reminders.  I had changed my keyword from `r` to `do` and typed `do this` as a test to make sure everything was working, and... you can see how the rest played out.
