### ISSUE TITLE
[FR] Better messaging on in-progress parsing 

### ISSUE THREAD

**Issue by loganrhyne** [surrealroad/alfred-reminders#39]
//Was: Date/Time related commands not working in Alfred 3 on OSX 10.11.5

Been using this for a few days and it's a great workflow! But I'm having issues where commands that start with a date keywork (today, tomorrow, or a date string) or simply a time (at 6pm) result in a "Reminder command not recognized" message. I looked at some other tickets and went through the more recent forum posts but couldn't find anything that worked.

I tried uninstalling and reinstalling and also repairing disk permissions and when I run 'rtest' get the output below (which seems to indicate that things are fine). What else can I do to provide info to help debug? Would love to keep using this as shared lists are an important part of my team workflows. Thanks!

Test results:
OS version: 10.11.5 (0 seconds)
Current date: Thursday, June 23, 2016 at 12:34:23 PM (0 seconds)
Initialize workflow path: /Users/lrhyne/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3598351E-2D79-4D11-9F23-2747AC0BD8C3 (0 seconds)
Initialize alfred-library: OK (0 seconds)
Initialize update-library: OK (0 seconds)
Initialize wf-library: OK (0 seconds)
Initialize plist-library: OK (0 seconds)
Reminders.app state: Running (0 seconds)
Fetch reminder count: 12 (3 seconds)
Fetch reminder info: OK (4 seconds)
Fetch reminder list count: 3 (0 seconds)
Fetch reminder list info: OK (0 seconds)
Run cache process: SKIPPED (0 seconds)
Fetch cache timestamp: SKIPPED (0 seconds)
Fetch cached reminder count: SKIPPED (0 seconds)
Test basic query: OK (0 seconds)
Test today query: OK (0 seconds)
Test in n minutes query: OK (0 seconds)
Test in n hours query: OK (0 seconds)
Test in n days query: OK (0 seconds)
Test in n days y hours query: OK (0 seconds)
Test in n hours y minutes query: OK (0 seconds)
Test at time query: OK (0 seconds)
Test tomorrow at time query: OK (0 seconds)
Test in x list query: OK (0 seconds)
Subtitle generation: OK (0 seconds)
Test basic reminder filtering: OK (0 seconds)
Test remind today reminder filtering: OK (0 seconds)
Test due tomorrow reminder filtering: OK (0 seconds)
Test reminder list filtering: OK (0 seconds)
Test version-check response: OK (0 seconds)
Current unix time: 1.46671047E+9 (0 seconds)
Simple JSON: OK (0 seconds)
Test execution time: 7 seconds

**Comment by loganrhyne** [comment]
After more playing with this I realized that I was just being thrown off by the error messaging and simply needed to continue through using the appropriate syntax. Probably doesn't even warrant an FR to improve the text flow here, but it would be nice if instead of giving the generic error, it instead went ahead with the nice parsed text response that you get once you've moved past the date/time portion of the syntax into the reminder text.

**Comment by surrealroad** [comment]
The options for doing so are somewhat limited, but I'll take another crack at it next time I go through the code.

**Comment by surrealroad** [comment]
Fixed in https://github.com/surrealroad/alfred-reminders/commit/2241da9e15bd6a16b90e10d71fec9e0a3f7d31ab
