### ISSUE TITLE
Documentation Request: build instructions

### ISSUE THREAD

**Issue by brandondrew** [surrealroad/alfred-reminders#40]
I'm made a few (trivial) changes to the code to accommodate UI preferences, but I'm unable to properly build the new bundle.  Could you include directions in the README.md for others like me who want to tweak things that Alfred does not expose?

I saved the `alfred_library.applescript` as a Script, and then zipped up my version with a `..alfredworkflow` extension, but it will not open in Alfred.  Any help would be appreciated—thanks in advance!

**Comment by surrealroad** [comment]
In Alfred, right-click the extension in the list and choose export.

**Comment by brandondrew** [comment]
If I start with the code on GitHub, there's no way to _import_ it into Alfred?

**Comment by surrealroad** [comment]
Oh I see. In that case, in Alfred create a new extension, then right-click and choose Show In Finder. Then replace all the files.
