### ISSUE TITLE
can not work in Alfred 3 again

### ISSUE THREAD

**Issue by Anotherbuzz** [surrealroad/alfred-reminders#41]
![Uploading Captura de pantalla 2016-07-14 a las 12.18.21 p. m..png…]()

hello, this workflow again fails to work. I have reinstalled it but it just can't work. and this is the result after running the "rtest":

Test results:
OS version: 10.11.6 (0 seconds)
Current date: jueves, 14 de julio de 2016, 12:09:45 p. m. (0 seconds)
Initialize workflow path: /Users/tuzi 1/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.93F11830-974E-4FCB-B100-45DCFAA18428 (0 seconds)
Initialize alfred-library: OK (0 seconds)
Initialize update-library: OK (0 seconds)
Initialize wf-library: ERROR: mkdir: /Users/tuzi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.surrealroad.alfred-reminder/: Permission denied (0 seconds)
Initialize plist-library: OK (0 seconds)
Reminders.app state: Running (0 seconds)
Fetch reminder count: 11 (10 seconds)
Fetch reminder info: OK (15 seconds)
Fetch reminder list count: 5 (0 seconds)
Fetch reminder list info: OK (0 seconds)
Run cache process: SKIPPED (0 seconds)
Fetch cache timestamp: SKIPPED (0 seconds)
Fetch cached reminder count: SKIPPED (0 seconds)
Test basic query: OK (0 seconds)
Test today query: OK (0 seconds)
Test in n minutes query: OK (0 seconds)
Test in n hours query: OK (0 seconds)
Test in n days query: OK (0 seconds)
Test in n days y hours query: OK (0 seconds)
Test in n hours y minutes query: OK (0 seconds)
Test at time query: OK (0 seconds)
Test tomorrow at time query: OK (0 seconds)
Test in x list query: OK (0 seconds)
Subtitle generation: OK (0 seconds)
Test basic reminder filtering: OK (0 seconds)
Test remind today reminder filtering: OK (0 seconds)
Test due tomorrow reminder filtering: OK (0 seconds)
Test reminder list filtering: OK (0 seconds)
Test version-check response: ERROR: La variable timestamp no está definida. (0 seconds)
Current unix time: 1.46846941E+9 (0 seconds)
Simple JSON: OK (0 seconds)
Test execution time: 25 seconds

**Comment by surrealroad** [comment]
ok it looks like it's getting thrown by your home folder being called "tuzi 1" and not "tuzi". Let me see if there's a good way to fix this…

**Comment by Anotherbuzz** [comment]
oh,because i just use the TimeMachine. I hope you could solve it, thanks a
lot

**Comment by Anotherbuzz** [comment]
hello, I've changed my home folder to "tuzi" and now it works again. thanks
for your suggestion.
