### ISSUE TITLE
Auto-update with OneUpdater

### ISSUE THREAD

**Issue by vitorgalvao** [surrealroad/alfred-reminders#47]
Currently trying the beta of this workflow. I see you have auto-update support as an item on your todo. I make [`OneUpdater`](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) which is a workflow-agnostic auto-updater, so you may want to try it.

There’s very little to setup, and once it’s done, you just forget about it. You literally just copy over and connect a `Run Script` node to your workflow, edit two variables, and it’s done. You then just release your workflow as usual, and it takes care of the rest.

![image](https://cloud.githubusercontent.com/assets/1699443/22132374/90f6fde8-deb1-11e6-8ccd-2b8fd61f15aa.png)

Normally I’d submit a PR, but since your method of distributing the workflow will soon have to change ([dropbox’s public folder functionality will cease working for everyone](https://www.dropbox.com/help/16)), I figured it’s best to open the issue first and then the PR if you want (though the whole point is this is easy to do yourself).

If you’re interested and have any doubts with the instructions, let me know!

**Comment by surrealroad** [comment]
Looks good!

**Comment by surrealroad** [comment]
@vitorgalvao I've added OneUpdater to https://github.com/surrealroad/alfred-reminders/commit/347ec2b4b6ca2fb4e745875e24450d878a993c83 however I don't seem to get any notification.

I changed the local workflow version from 70 to 12 (lower than the currently published 63), but did not get any notification when actioning the workflow, and didn't see any messages in the debug console.

**Comment by vitorgalvao** [comment]
@surrealroad You have `frequency_check` set at `15`. So if you change the version today, it resets the counter and it’ll only check for a new version 15 days from now. That’s why you’re not seeing any error messages — everything is working as expected.

Change `frequency_check` to `0`, for testing, and it should check every time.
