### ISSUE TITLE
Persist the preview when not all information is present yet

### ISSUE THREAD

**Issue by Nibblesh** [surrealroad/alfred-reminders#49]
typing 'r at 12' will change from the preview snippet to a google search as there aren't all of the parameters available.

Would it be possible to maybe have some indicator if the reminder is valid or invalid (maybe a tick or cross), but to keep the workflow active while it is invalid so that you still know that the workflow.

I have just started using this, and was attempting to create a reminder for a lunch event, so when i typed 'r at' the preview was there, but after writing 12 it went to a google search preview, which made me think that I did something wrong.

Maybe some visual feedback that you're still on the right track would be useful for new users.

**Comment by surrealroad** [comment]
This is what should be happening, so something is broken. I'll look into it.
