### ISSUE TITLE
Problems about alfred's access to reminders

### ISSUE THREAD

**Issue by DFY8054** [surrealroad/alfred-reminders#53]
The system of my mac is macOS Sierra 10.12.2 Beta. 
When a create a new reminders through Alfred,  there is a window asking me whether allow alfred to access to reminders. I click OK, but it still there.
![screen shot 2017-06-01 at 2 13 38 pm](https://cloud.githubusercontent.com/assets/11442129/26666818/9269074e-46d4-11e7-9144-132cc2f7f5c8.png)
I want to know how to solve this problem.

**Comment by DFY8054** [comment]
Besides, I have set my privacy to allow this access. But it still doesn't work.
![screen shot 2017-06-01 at 2 16 09 pm](https://cloud.githubusercontent.com/assets/11442129/26666879/e19c3192-46d4-11e7-82e5-59c5745439c7.png)

**Comment by surrealroad** [comment]
You most likely also need to check `osascript` there too.

**Comment by DFY8054** [comment]
I have checked this too, but It seems that it still doesn't work.

**Comment by jiangyewen** [comment]
I encountered the same problem. The reminder privacy alert view keeps asking and never dismiss until I choose Don't allow... This makes this workflow useless... Hope this can be fixed soon

**Comment by mariuszlabedzki** [comment]
Unfortunately I have the same problem - I need click "OK" about 20x to allow Alfred access to Contacts.

**Comment by AleksIralda** [comment]
Almost a year and there is not solution

**Comment by surrealroad** [comment]
Presuming everyone with this issue followed the instructions on the readme, then your issue is with the OS or _possibly_ Alfred, but almost certainly, not this workflow.
