### ISSUE TITLE
Support for High Sierra

### ISSUE THREAD

**Issue by odajay** [surrealroad/alfred-reminders#59]
When you try to enter a reminder in High Sierra, unfortunately nothing get saved despite validating with Return.

**Comment by surrealroad** [comment]
this has been working in high sierra beta up until beta 7, I'm going to try beta 8 tomorrow and see if the problem persists.

**Comment by KyleKing** [comment]
I have the same issue. When I press enter nothing happens. I played around with the debugger and looked through the code, but I'm not sure where to look

![df6f92a8-63c9-49de-bdff-ac0fb25e86ea](https://user-images.githubusercontent.com/3784339/29849898-dc7f2dc2-8cf7-11e7-93cb-dacdaafb9aaa.png)


I installed the latest alfred-reminders release and am running beta 7

**Comment by surrealroad** [comment]
Confirmed this is the case for beta 8 as well. I'm not sure why this is happening.

**Comment by bw352** [comment]
@surrealroad - Were you able to solve the parsing problem? I, too, have the problem of nothing happening after I press enter.

Thanks.

**Comment by surrealroad** [comment]
this should be fixed in Alfred 3.5 build 874 (currently pre-release)
