### ISSUE TITLE
Two easy to implement feature ideas :-), but very helpful ones

### ISSUE THREAD

**Issue by scherbaum** [surrealroad/alfred-reminders#60]
Great work, thanks! 

Two easy to implement feature ideas, which would be great if they could be integrated
-----------------------------------------------------------
- allow usage of 'in 3d' (= in 3 days), analogous: in 1w 1m 1y  etc. or even shorter i3d
- I love that application-contents can be stored as reminders. It's perfect for email todos and keeping the mailbox clean. However: "r this " is very cumbersome to type, it would be way better if one could use a hot key for application reminders or type 'rt'   

Many thanks & cheers
Kristina

**Comment by surrealroad** [comment]
First point won't be addressed. 

To the second point, see https://www.alfredforum.com/topic/917-reminders/?do=findComment&comment=53567
