### ISSUE TITLE
Error: Application isn't running

### ISSUE THREAD

**Issue by djspiewak** [surrealroad/alfred-reminders#65]
I'm constantly getting this error now.  macOS 10.13, Alfred 3.5.1.  Basically any time I create any sort of reminder, this is the error that it produces.

**Comment by dvdvdmt** [comment]
Could you provide an error log from debug console?
https://gfycat.com/gifs/detail/PlayfulVillainousLacewing

**Comment by djspiewak** [comment]
So I went to give you the debug log, and… it worked.  I tried a couple of different reminder creations and they all worked, both with and without the log open.  So… weirdness?  Sorry for the distraction!
