### ISSUE TITLE
Fails when the tasks list is inside a group

### ISSUE THREAD

**Issue by ilyasToumlilt** [surrealroad/alfred-reminders#86]
Let's take this Reminders setup example,
![Screenshot 2020-06-06 at 20 44 33](https://user-images.githubusercontent.com/7683628/83952135-f3c9a400-a836-11ea-8b76-27c03c701088.png)

When adding a task to the "INBOX" list, which is not in a Group, everything works well.

Then, if I set "Work INBOX" which is inside "Work" Group as default reminders list, the workflow script fails with `NSAppleScriptErrorNumber = "-1728"` with `NSAppleScriptErrorMessage = "Reminders got an error: Can\U2019t get list \"Work INBOX\".";`.

Error thrown by `Run Script` line 45.

**Comment by limakzi** [comment]
This issue is still present on the latests Alfred version, latests Alfred Reminders version and Big Sur.
